# Yarn Berry configuration for Summerhouse frontend
# Using node-modules linker for better compatibility with Next.js

nodeLinker: node-modules

# Enable compression for faster installs
compressionLevel: mixed

# Telemetry off
enableTelemetry: false
